backend:
  name: git-gateway
  branch: master
publish_mode: editorial_workflow
media_folder: "img/uploads"
logo_url: https://tometo.org/img/tome.png
display_url: https://tometo.org
collections:
  - name: "updates"
    label: "Updates"
    label_singular: "Update"
    description: "News posts"
    preview_path: "updates/{{number}}-{{slug}}"
    folder: "updates"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Tags", name: "tags", widget: "hidden", default: "update"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime", format: "YYYY-MM-DD"}
      - {label: "Layout", name: "layout", widget: "hidden", default: "update.njk"}
      - {label: "Update Number", name: "number", widget: "number"}
      - {label: "Author", name: "author", widget: "string"}
      - {label: "Description", name: "description", widget: "string"}
      - {label: "Text", name: "body", widget: "markdown"}
